name: Deploy Snapshot

# Run workflow on commits to the `deploy` tag
on:
  push:
    tags:
      - deploy

jobs:
  deploy-snapshot:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
           cache-name: cache-maven-repo
        with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-${{ env.cache-name }}
           
      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
           distribution: zulu
           java-version: 15
           gpg-private-key: ${{ secrets.gpg_private_key }}
           gpg-passphrase: MAVEN_GPG_PASSPHRASE
           server-id: ossrh
           server-username: MAVEN_USERNAME
           server-password: MAVEN_CENTRAL_TOKEN
           
      - name: Build and Test
        run: mvn -B clean test
      
      - name: Package
        run: mvn -B package --activate-profiles deploy
      
      - name: Deploy to oss.sonatype.org
        run: mvn -B deploy --activate-profiles deploy
        env:
           MAVEN_USERNAME: ${{ secrets.nexus_username }}
           MAVEN_CENTRAL_TOKEN: ${{ secrets.nexus_password }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
